---
common:
  log_file: qqbot.log
  captcha_file: captcha.jpg
  qq: '10000'
  password: 123456
  bot_name: QQBot
  masters:
  - 10086
font:
  name: 微软雅黑
  size: 12
  color: '000000'
  bold: 0
  italic: 0
  underline: 0

