---
common:
  log_file: qqbot.log
  captcha_file: captcha.jpg
  qq: '2833971744'
  password: 17A81E38
  bot_name: 晒晒子
  masters:
  - 396893752
font:
  name: 微软雅黑
  size: 12
  color: '000000'
  bold: 0
  italic: 0
  underline: 0

